services:
  - type: web
    name: hospital-appointment-api
    runtime: docker
    rootDir: HospitalAppointmentSystem.API
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production